site_name: hoppr-cop
repo_name: hoppr-cop
site_dir: site
repo_url: https://gitlab.com/lmco/hoppr/utilities/supply-chain-security/hoppr-cop
copyright: "Copyright (c) 2022 Lockheed Martin Corporation"

nav:
    - Home: index.md
    - Install: install.md
    - Python Library: python-module.md
    - Contributing: contributing.md
    - Development:  development.md
    - License: LICENSE.md

#markdown_extensions:
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:mermaid2.fence_mermaid
#  - pymdownx.tabbed:
#      alternate_style: true
#  - attr_list

theme:
  name: material

extra_css:
    - 'docs/css/termynal.css'
    - 'docs/css/custom.css'

extra_javascript:
#    - https://unpkg.com/mermaid/dist/mermaid.min.js
    - 'docs/js/termynal.js'
    - 'docs/js/custom.js'


#plugins:
#    - mermaid2:
#        arguments:
#          theme: 'dark'
